### ISSUE TITLE
submodule을 적용한다

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-pium#354]
# 어떤 이슈인가요?

> 다음 discussion으로부터 도출된 issue 입니다.
- https://github.com/woowacourse-teams/2023-pium/discussions/324

기존에 jenkins 서버 내부에 설정파일을 관리하면서 다음과 같은 문제가 발생했다.

- 캠퍼스 외부에서 properties / env 파일 관리 불가
- properties 설정을 파악하기가 어려움 (vim, cat 명령어로 확인)
- 분업화 진행 간 properties / env 파일 변경에 대한 공유가 어려움

# Todo

private repository를 이용하여 submodule 환경을 구축한다.

- [ ] env파일 관리
  - [ ] local / prod / dev 파일 분리
- [ ] properties 파일 관리
  - [ ] local / prod / dev 파일 분리

다음 Organization을 활용한다.
- https://github.com/organizations/pium-official/settings/profile
